### ISSUE TITLE
Quiz/Homework 1

### ISSUE THREAD

**Issue by john-csudh** [csudh/toro-net#1]
# Introduction

Need to evaluate and make a decision on stack framework:

- MEAN
- Java/String Boot
- Python
  - Flask
  - Django
- MERN
- Clojure 
- Others?

With the following criteria:

- Skills
- Features
- Constraints
- Usability
- Support/community
- Security
- Complexity

## TODO

- [ ] Paper evaluation: create a scoring matrix `0` (bad) to `5` (excellent) of framework and criteria
- [ ] Handson evaluation: pick one and do a simple toy project:
     - Login
     - Scaffolding (optional)
- [ ] Evaluate documentation process

**Comment by Felixwhwang** [comment]
**Requirements Group Evaluation**

![group evalution](https://user-images.githubusercontent.com/31264160/30352261-e1a32506-97d3-11e7-9262-3b8bfa81de04.png)

**Comment by mattlevan** [comment]
![image](https://user-images.githubusercontent.com/4582375/30355067-b72ffe36-97e5-11e7-9786-5ada6d989cf6.png)

**Comment by juancleon** [comment]
Testing Team
 
Technology	|	MEAN	|	JAVA Spring	|	Python Flask	|	Python Django	|	MERN	|	Clojure
--- | --- | --- | --- | --- | --- | ---| 
Skills	        |	3	|	3	|	3.1	|	2	|	2	|	2
Features   	|	4	|	4	|	3.8	|	4	|	5	|	4
Constraints	|	2	|	5	|	3.1	|	3	|	4	|	4
Usability   	|	3	|	0	|	2.5	|	2	|	4	|	4
Support/Comm. | 3	|	5	|	4	|	3	|	5	|	4
Security    	|	2	|	3	|	3	|	3	|	5	|	3
Complexity	|	3	|	0	|	3	|	3	|	4	|	2
AVERAGE	        |    2.86	|	2.86	|	3.21	|	2.86	|	4.14	|	3.29


Toy Project Comments:

Spring (Juan): Spring seems easy to use at first when looking at the guides online but it proved to be more difficult than expected. The necessary installations, configurations, and dependencies seemed to never end. Not to mention importing the necessary libraries and configuring the PATH and CLASSPATH variables repeatedly. Granted, I also chose to install and configure an IDE I have used only sparingly in the past. That added to the list of tasks to complete. Also, the notation used in the guides online is shorthand and not very explicit. Spring depends on the build system Maven which is a project unto itself to install and configure. Going back and doing the research to score Spring I came across a guide that is simpler and doesn’t necessitate using an IDE. The directions and instructions make much more sense now that I’ve gone through the process once.
 
Spring documentation: The documentation for Spring is very good at it has been around for 15 years.
 
MERN (Navkaran): My comment would be that since professor want the Single page Application only MERN is the best one that we can use for that particular feature, also overall MERN is better only problem here is that we have to learn MERN framework from basic. That is the reason I gave MERN skills 2 points. It has better features and compatibility than all others.
 
MEAN & MEARN (Nikhil):
 
MEAN:
Angular uses two-way data binding and a digest cycle. Which makes it slower than React.
Angular enforces MVC like design. Better organised coding.
 
MEARN:
React uses unidirectional flow to efficiently keep changes. It’s faster in performance than
Angular.
React makes easy it develop UI. But it’s just a library. It is up to user to how to maintain your
structure and data. It can make code harder to maintain.
Facebook holds the licensing of React.js. Open source??
 
PYTHON DJANGO (Ishu):
I was more comfortable in java spring than the framework that I was given i.e. python Django. Though python Django has more feature in it but skills for java spring are better than the skills in python Django. Python Django has more features but overall java spring is better.
 
Shout-outs: Thank you to Navkaran and Nikhil for showing up to our scheduled meeting on time and contributing throughout. Thank you Navkaran for researching frameworks other than the one assigned to you. Also, thank you to Ashish for being the first to respond to the call to action email.

**Comment by maefranco** [comment]
![untitled](https://user-images.githubusercontent.com/25971844/30355398-0b12fa38-97e8-11e7-9a0d-1f4fa662f831.png)

**Comment by Janani1989** [comment]
![hw1](https://user-images.githubusercontent.com/25727577/30450761-c4cd82ea-9946-11e7-81a3-ce73dc19575a.png)

**Comment by john-csula** [comment]
Please select `vuejs` or `angular` or `react` and comment on why you've selected one that you've selected.

**Comment by FlyBono24** [comment]
I would put Vue as #1, Angular as #2, and React as #3:

- Angular/React would be more helpful to learn in the long run, because they are used industry-wide.  But for the **scope of this class** only, I will pick Vue.
- Vue is faster to render, quicker to learn, and quicker to start up projects.
- Angular would be 2nd because it's slightly easier to learn than React, and has industry support.
- React would be 3rd only because of the learning curve involved, and it's newer to the industry so it has slightly less support right now.

--Ryan Marquardt, The Architecture Team

**Comment by john-csudh** [comment]
All, I forgot to talk about documentation tool.  Unless people are vehemently against it, I am going to the [wiki](../wiki).  Give us a 👍 or 👎 please.

**Comment by Arpitha93** [comment]
My first preference is Vue , Second - Angular and, Third - React. 
Though Angular or React is very popular and widely used, for our short term class I would suggest to go with Vue. Here are few advantages of Vue over React and Angular.
•	Vue usually slightly ahead due to its lighter-weight Virtual DOM implementation.
•	Vue is a more flexible, less opinionated solution ( than Angular ).
•	There are many tools in Angularjs and so many complex syntax that it can confuse you sometimes. On the other hand,  Vue.js is much simpler than Angular and sometimes even better. 
•	Vue is much simpler than AngularJS, both in terms of API and design.
Here is a small survey that I went across and noted the points, I would like to share the file for the reference which gives the detail why I picked Vue.
[React,AngularVsVue.docx](https://github.com/csudh/toro-net/files/1304189/React.AngularVsVue.docx)

**Comment by Janani1989** [comment]
Front-End Framework:

I have listed my preferences below by ordering them according to their ranks that are based on my research.

1. Angular js: Very widely used. Very good support and relatively easy to learn when compared to react. Rich library as well.
2. Vue js: Easy to learn and implement, given the time constraint of our project. A good mix of Angular and React. The main drawback as lack of good support/community when compared to others.
3. React js: Although a successfully emerging technology, it seems like little difficult to learn and adapt.

On a side note, although everyone might have different opinions on different frameworks, when it comes to front-end, I think the votes from #Frontend Team matter a lot as they are going to contribute more.

Janani Janardhanan.
Backend Team

**Comment by carlhub** [comment]
__Technology Preferences:__

1. __`Angular`__   My top choice is Angular because it is a seasoned framework backed by a large company, Google, as well as having rich support from the development community.

2. __`Vue`__ - While it is an  easy to learn framework, I haven't read much about its scalability strengths and that is crucial to our project.

3. __`React`__ - Looks very interesting and it's a hot technology but I think it can become very challenging for the tight deadline we have to deal with.

Overall Im excited about all technologies but given our time constraints and requirements I vote for Angular. My second choice was Vue, followed by React.

> _--Carlos Ontiveros, Backend Team_

**Comment by hugoLucas** [comment]
My main preference is **React**. 

1. React: its supported by the current king of SPAs so that's a big plus. However using MERN.io will mean we will have to pick up Redux which has a big initial learning curve. React w/ redux makes debugging data issues much easier than using plain Angular though.

2. Angular: much more intuitive to learn and use. It's supported by Google and one of the most popular front-end frameworks so having it on our resumes will look nice. 

3. Vue: looks simple but it does not have the extensive documentation and support community of Angular or React. 

Hugo, Architecture Team

**Comment by rkaur19** [comment]
I am confused between Angular and Vue
1. Angular: it's not as easy as Vue but there is a lot of support as it is by Google and is very scalable but it has a huge library so learning can be time consuming
2. Vue: easy to learn but not much help and support compared to both Angular and React
3. React: not enough time to learn otherwise it would have been a great learning experience 

Ramneet Kaur, Frontend Team

**Comment by awangca** [comment]
My preferences: 

1. React:
   --Better performance with data processing
   --Low learning curve ( good for beginners )
   --Easy maintenance of isolated components
   --job interests about react is growing fast than Angular (Good hands-on experience to put on Resume）
 

2. Angular:
   -- Learning curve is medium
   --But with better documents and architecture
   --Two-way data binding
   --More work with debugging

3. Vue:
   --Simplified Angular
   --But with less support

By Anyi Wang, FrontEnd Team

**Comment by genriquez1** [comment]
Ranked in my order of preference: React , Angular , Vue  
1. **React**: 
- Faster performance than both Angular and Vue 
- Easier to debug and use in large groups 
- Growing support community and countless sources given from facebook and available on youtube to 
  watch. Thus making the learning curve moderate.
- Although it may be more difficult to get started on, the demand for job is increasingly growing and will be helpful down the line having experience in this framework now for the real world.

2. **Angular**: 
 - Comes with an abundant library that allows for flexibility and Scalability of our SPA.  
 - When taking maintainability into account it would be good in large groups
 - More ideal for documentation
 - Great support community
 - Will be more difficult to debugging because finding errors could be tricky
 - However Angular 2 could be set back by angular 4 and loose support overtime

3. **Vue**:
 - Low learning curve, easy to get going 
 - Community support is nearly nonexistent 
 - Maintainability and Scalability are key issues to watch with it. 


Gerardo Enriquez , Frontend Team

**Comment by nolanruss** [comment]
1. __Vue__ - It has a lower learning curve, which is good for us, and it has everything we need.  Working in Vue templates is easier to understand for new developers.  Also, MEVN is gaining a lot of interest right now.
 2. React - It is less complex than Angular, has a number of resources and tutorials available.
 3. Angular - The large number of features in Angular contributes to its complexity, which I think will hamper development for our short timeline.

There are tutorials for getting started with all of these technologies available to us through Lynda.  I think Vue is the best fit for our class.

__Nolan Thompson__ - _Architecture Team_

**Comment by kpuniani** [comment]
Ranked order in terms of preferences-
1.Angular- Good to learn according to industry perspective, has better structure and foundation.
2.Vue - Learning is easy as compare to Angular and React, but has less support
3.React- Provides more support, tools but has very steep learning curve

--Karan Puniani, Frontend Team

**Comment by mattlevan** [comment]
# My vote is for Vue.js

## Evaluation Summary
### Vue.js
Vue is [easy to learn, simple to use](https://hackernoon.com/angular-vs-react-the-deal-breaker-7d76c04496bc), [uses a template-based system](https://deliciousbrains.com/vue-vs-react-battle-javascript/) which will fit perfectly with our "cards", has [plenty](https://blog.sicara.com/a-progressive-web-application-with-vue-js-webpack-material-design-part-1-c243e2e6e402) [of](https://jeroendruwe.be/travel-example-vue-js-single-page-app/) [SPA](https://github.com/skyronic/vue-spa) example projects and [tutorials](https://laracasts.com/series/learn-vue-2-step-by-step/episodes/26) available online, and provides all of the above while being less complex (our app is relatively simple to what most tech companies build), lighter weight, and [even a bit faster than React](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html).

### React
React is a tempting option because of its [massive popularity in 2016](http://stackoverflow.com/research/developer-survey-2016), as well as its close relationship with Facebook, which is likely the most widely used SPA of all time. If it works for Facebook, certainly it can work for us, right? Well... I'm not so sure. Many evaluations I've read online tout React's superb performance, popularity, support, and extensibility, but many also note its steeper learning curve when compared with Vue.js, see [one](https://medium.com/@harryho2/angular-vs-react-vs-vue-f470f5b74bf6), [two](https://www.quora.com/Should-I-learn-React-js-or-Vue-js-Is-it-worth-it-if-I-learn-Vue-js-first-and-then-React-js), and [three](https://www.codementor.io/pavel450/debate-vuejs-vs-reactjs-9p5a4q2pd). I have no doubt we could get up and running with React, I just think it will take longer and provide unnecessary complexity for the application we must build. 

### Angular2/4
When John described Angular as a "one stop shop", my ears definitely perked up. I am a lover of Costco-- my favorite "one stop shop"-- so if Angular is anything like Costco, I thought, how could we go wrong? Reading more about Angular, and thinking more about Costco, however, led me to vote against it. If you've ever shopped at Costco, you might have noticed that _there are no aisle signs_ for guiding customers to the products they want. Since Angular [uses the JavaScript DOM rather than a Virtual DOM like React and Vue.js do](https://www.agriya.com/blog/2017/03/08/angularjs-vs-vue-js/), the programming model is more complex, and I'm concerned that working with Angular might be kind of like shopping at Costco: we can find everything we want, but it might take awhile and you'll have to stop at the food court for a hot dog and frozen yogurt half-way through! [This article](https://www.valuecoders.com/blog/technology-and-apps/vue-js-comparison-angular-react/) certainly validates that concern. Angular will also be doable for us, I'm sure, but, again (as with React): why use a heavier framework when a lighter one provides everything you need for the app you're developing?

**Comment by Gurkiran-Singh** [comment]
1:- My main preference is Vue because it is easy to implement and understand and  it has everything that we need .

2:- Angular :  Rich in features but not easy to understand according to the time we have for project.

3:- React : It is good and fresh but not easy to learn in short span of time.

**Comment by mtheeb** [comment]
I'm voting for Vue, for those reasons:

- Ease of understanding and development, which serves the purpose of this class. 

- Flexibility, user can write a quick app and run it straight from the browser. Also, this flexibility makes it easy to switch from React, or Angular to Vue. 

- Vue perform faster than Angular and React.

- Comprehensive documentation, Vue has a very thorough and well-written documentation.

Mohammed Althubyani,
Backend team.

**Comment by Felixwhwang** [comment]
## My preference is **Angular**
1. **Angular** - Most used one than the others; based on components; large community; easy code integration; more powerful framework to build single-page app; more challenge.
2. **Vue** - Not enough features to build single-page app which handles data from server you will need additional tools and libraries for: routing, state-management, server communication, even if it is easy to start.
3. **React** - Utilize a virtual DOM; provide reactive and composable view components; maintain focus in the core library; It is kind of similar to **Vue**, but it can’t create a powerful application with full-featured server side.

> Wenhao Wang, Requirements Team

**Comment by Alexander-Ing** [comment]
My preference is React.

React - Although React has a steep learning curve I believe it would be a good learning experience for the team. As others have pointed out React has gained a lot of popularity, using React for this project would allow those interested in web dev an opportunity to test out and learn this new tech. I understand that we are trying to emulate a work environment by choosing a more comfortable language, but in this case I feel the learning experience and resume building opportunity is too good to pass up.

Angular2 - This is my second choice, one of the more challenging aspects of React is the fact that a lot of the functionality needs to be imported from external libraries, but Angular has all that built in. This is a huge plus as it will cut down on confusion and the major head aches that comes with all those external libraries. Angular is also a very popular language that is sought after in the job market so the difference in choice from react to angular is very minimal, I am fine with either language being chosen.  

Vue - Very easy to pick up and get something running, would be easier to set up and less confusing to get started on our project. The fact that it is simpler to understand is its biggest draw, the team would be able to pick it up and just start much faster compared to the other languages.

**Comment by DevRockstarr** [comment]
**1. Vue.js** 
According to me vue.js is a progressive framework and is very useful if you are a new web developer. It is easy to learn and most of the websites in China are using this including Alibaba.com. So, I think it is a good framework to learn and will let you stand different from the crowd.

**2. React.js**
It is very tempting as it is used by the facebook, but at the same time it has a steep learning curve. A good and established support is available for this framework. It can be implemented for what we need for the project.

**3. Angular.js**
Angular is a much easier to implement. It has all the functionalities built-in and is most trusted and reliable of all the frameworks, just because it is owned by google. I have used angular earlier and I want to foray into another framework. So, it will be my last choice.
My Priority:
1. Vue.js   2. React.js   3. Angular.js

> Sahil Thakur, Backend Team

**Comment by NickVispute** [comment]
## Technology Preference ##

### **1. Vue:**
- **Lower learning curve** compared to others(Angular and React).
- Vue is quick, reactive, very flexible with rich libraries.
- Increasing community support.  Good documentation.

### **2. Angular:**
- one of the hot technologies in the market.
- Vast community support. 
- 'All-in-one' package. But can be confusing (complex) for beginners.

### **3. React:**
- **Steeper learning curve** compared to others(Angular and Vue).
- Fast performance, easy to maintain, easy to debug.
- Hot technology, connected to Facebook, large community support available.

--  __Nikhil Vispute__ - Testing Team.

**Comment by juancleon** [comment]
My preference is Vue. The learning curve is much less steep. If you're familiar with JavaScript and HTML you can start building non-trivial applications in less than a day. However, with Angular and React, the learning curve is much more steep. The framework of Angular is simply huge and as a user, you will need to become familiar with many concepts before becoming productive. The complexity of Angular is largely due to its design goal of targeting only large, complex applications - but that also makes the framework much more difficult for less-experienced developers to learn.

Juan Leon, Testing Team

**Comment by sugandhaarora** [comment]
**My preference is Vue.**

**Vue**: It does not have much support but it is simple, emerging and easy to learn and integrate with other libraries.
**React:** It is a big library and a bit complex. It has more support and work done but it has a steep learning curve.
**Angular:** It is framework, widely used, has strong support and documentation, rich in library but medium learning curve for out short timeline. Also it is complex and has a heavier framework.

Sugandha Arora, Backend Team

**Comment by fa1234** [comment]
My preference is Vue.


1. Vue: it is the first choice for me because it is an easy and fun framework to use. It is smaller than React and Angular, so we can learn more concepts and ways to use.

2. Angular: a powerful framework with much support but it not easy to learn. We need time to learn it because Angular is big and complicated. With multiple ways to do the same thing, it is hard to tell which way is better. 
3. React: a big framework with a great support but still, it is complex and hard to learn. 

Faisal Alharbi,  Backend Team.

**Comment by NasserAi** [comment]
**My vote is for Angular**

**1-Angular.** From what I have seen, Angular is the current trend in web development. Most of the web development jobs are asking for "Angular familiarity". I believe going with Angular will give us the opportunity to be familiar with it, and have a deep knowledge of its functionalities in a serious development environment. Angular for the future and job interviews.

**2- Vue.** I did a little research about it and I found that it is not difficult to learn, light framework, and its routing system is stable and easy to use. The only concern is, we might don’t have enough time (as a class) to catch up with learning it.

**3- React.** It has some similar features to Vue.js. Less complex than Anguler, but also has less community support.


-Nasser
(Requirements team)

**Comment by hbrar1** [comment]
My preference is Vue because Vue is simpler, it features a lot of concepts from Angular 1 and React. We can use it without any build system just include it into HTML file.

Angular: Good Framework to build SPA. It is  supported by Google 
It advocates global community support, is a complete framework and encompasses a a very good feature i.e. two-way data bind.

React:  JSX makes it easy to read the code of your components. 
We can also integrate some tools like JEST.We can render React on the server-side.It can also be used with any framework (Backbone.js, Angular.js) as it is only a view layer


Harmanjeet Singh Brar.
Testing Team

**Comment by vm919** [comment]
**Angular:**
Although, in a way it is a complete solution and makes the code very well organised, still it has a very steep learning curve.

**React:**
It seems to be the case that React in a way has more advantages over Angular as it is still the oldest of all and provides more detailed and mature solutions. React is more indiscreet whereas Angular is more stringent.

**Vue:**
It is simple, and seems to be in the middle of the other two as it provides a thoroughgoing solution and provides the the freedom to pitch the choice of preference. 
**------------------------------------------------------------------------------------------------------------------**

Angular, by a great amount is the largest, React is intricate whereas Vue is intelligible.

Based in my exploration of the above three, I would choose Angular because I have always been interested in object oriented programming and typescript. Moreover it dispenses the developers to learn from experts via open source community and works on client side,and is secure to be implemented on the front end of any application.

Vaibhav Mishra,
Requirements Team!!

**Comment by maefranco** [comment]
**My preference is Vue.**

When considering the three possible frameworks, two expressions came to mind: "Failure is not an option." and "Time is of the essence." We need to use a framework that can get the job done within the 2.5 months that we have. Vue is the easiest to learn, and there are examples of and tutorials on creating SPAs with Vue. It's true that the Vue community is much smaller than Angular or React, but I'm hoping that the available support will be sufficient because it's the easiest to learn out of the three. From what I've been reading about the three frameworks, it seems like Vue incorporates some aspects of both Angular and React, so if we choose to learn either one in the future, the transition from Vue to either framework could be easier.

My ranking of the three:
1. Vue - easiest to learn
2. Angular - easier to learn
3. React - hardest to learn

Mae Franco - Frontend team

**Comment by navkaran4565** [comment]
Vue- Its template is straight. It’s quite stable and easy to use. It holds on to web technologies and builds on top of them. Vue is much simpler than angular in terms of API and design and also in terms of complexity Vue is not that complex as React. Vue is more flexible so this is my preferred framework.
React- Everything is java script here. It has a fast UI. React is complex if we compare it with Vue. It can be challenging at the start.
Angular- It is a good framework for Single page applications, however it is more complex and immense. I will prefer Vue over it. There are many many features in it and it’s difficult to tell which one is the best.

Navkaran Singh Sandhu     (Testing Team)

**Comment by ghost** [comment]
Of the three frameworks, Angular and React are popular among tech companies and very much in demand. So I feel it is better to choose one of these options. Therefore **my first preference is React.**

First : React
1. It has a low learning curve
2. It is gaining popularity and it is used by well known companies
3. It has a good community support
4. In regards to performance, react is good.
5. It is a lightweight library

Second : Angular
1. It is widely used by many companies
2. It is a bit more bulky
3. It contains more features

Third : Vue
1. It is not as popular as angular and react in the tech field
2. It has a low learning curve

Archana Mohan (Front End Team)

**Comment by RauKevin** [comment]
1st ANGULAR
2cd VUE
3rd REACT

- Initial impressions, both angular and Vue have a simpler look and feel. 
- Developers familiar with HTML, CSS and JS experiences may feel more comfortable with angular and Vue. 
- Angular has the highest amount of tutorials, support and documentation
- Angular has more functionality than Vue without the need to bring in additional libraries 
- REACT is only cool because Facebook uses it

**Comment by jielichen18** [comment]
Evaluation Result:

NO 1:  Angular JS
-	Dependency injection: inherits any standard functions;
-	Data Binding: helps us write less boilerplate code to create interactions between components;
-	More Github Contributors and Github Stars.

NO 2: React JS
-	The one-way data flow helps with maintainability and keeping data and DOM elements consistent;
-	More community support compared with Vue.js.

NO 3: Vue.js
-	 Absence of pedigree; It is fresh and has little baggage. The way we see it, Vue.js is lightweight & easy to learn.

Jieli Chen 
Backend Team

**Comment by john-csudh** [comment]
@Felixwhwang Please take a look at https://github.com/csudh/toro-net/wiki/requirements.md and update https://github.com/csudh/toro-net/wiki/requirements.md/_edit#frontend-selection base on the information count above.  Note that `xx` is the count of what people have been voting for each of the categories.

**Comment by john-csudh** [comment]
Folks, if you have not voted by ranking your first, second or third choice along with a comments on why you've selected what you've selected, please do so now.  Not participating will impact your grade.  You have until Sunday night to complete this.

@Felixwhwang please continue to monitor this discuss and update https://github.com/csudh/toro-net/wiki/requirements.md/_edit#frontend-selection as counts are coming in.  We will have a hard cut off by 10:00 PM Sunday.  Votes after this time will NOT count.

**Comment by ErnestUrzua** [comment]
## Evaluation Result:
Speaking strictly from a project specific point of view, I only consider what will be affecting the project immediately and how it would benefit us in completing it for this term.

1. **Vue** 
good for beginners, yet powerful enough to carry out the requirements needed for this project.  Being able to get up and running, creating content is exactly what we need for such a short period of time. The fact that Vue is less constraining in solving problems in comparison to Angular, this gives us room to create code that can be done many ways. 


2. **React**
The advantage of having speed, robustness is outweighed by its difficulty to get off the ground, especially for novices.  There is a place for React but for our purposes I believe a smaller-easier toolset is best. 

3. **Angular**
Because Angular is considered a more formal architecture, thus aimed at a particular application structure, this can prove difficult if we try to do anything different. For this project I'm not sure if we're going to encounter this scenario, but I'd rather avoid it altogether if possible.


## Conclusion
**Vue**
Angular
React

**Ernest Urzua**
**Architecture Team**
