### ISSUE TITLE
Backend Requirements

### ISSUE THREAD

**Issue by john-csudh** [csudh/toro-net#16]
## Background

We need to document a contract between the front-end and back-end team.  Draft a REST API which should include end-points and payload description for `users`, `posts`, `session`

CRUD should contain:
- List 
  - All
  - Partial (segmentation)
- Read single 
- Update single
- Delete single
- Create single

## TODO

- [x] Create a wiki page
- [ ] Define actions for `sessions`
- [x] Define CRUD actions for `users`
- [x] Define CRUD actions for `posts`
- [ ] Sample request for each of the above
  - [ ] `GET` request
  - [ ] `POST` request + payload

**Comment by mattlevan** [comment]
Hi @Janani1989 and @maefranco, will you guys (or any of your team members) provide a quick recap/summary of your meeting from earlier this week here please? Thanks!

**Comment by Janani1989** [comment]
Hey @mattlevan , we discussed about the CRUD actions for users especially the request and payload for each endpoint. After getting an idea of how endpoints work by drafting 4-5 endpoints, both the teams decided to work on the rest of the endpoints during the week and share our ideas on a slack channel that we created exclusively for both the teams. Please refer the backend wiki page for updates.

**Comment by ghost** [comment]
@Janani1989  Hi, are you hiring? I am going to be a student there in the Fall, but I have a lot of experience in Full Stack and DevOps. I am looking for a job as a developer at CSUDH. Is there a way you guys can integrate me into your team? I have experience with MEAN and LAMP stacks , and other web technologies.
