### ISSUE TITLE
Create architecture page

### ISSUE THREAD

**Issue by mattlevan** [csudh/toro-net#5]
## Todos

- [x] Demonstrate the system from a high level, including how the frontend and backend interact
- [x] Make diagrams
- [x] Discussion of system
- [x] Organize high level architecture overview for class tomorrow
- [x] Provide data flow from browser to database
